#!/bin/bash
# mysql -h172.30.46.13  -udeveloper -P3307 -pwt2apsdev2013 appshare_reco

if [ x${1} = x'21' ];then 
    PARAMS="-h192.168.1.21 -utjx -p94E5696b appshare_reco"
elif [ x${1} = x'22' ];then 
    PARAMS="-h192.168.1.22 -P3308 -utjx -p94E5696b ecmall "
elif [ x${1} = x'201' ];then 
    PARAMS="-h192.168.1.201 -P14301 -ulbs -pB997354A42990D94 appshare_log"
elif [ x${1} = x'elk' ];then 
    PARAMS="-hlocalhost -uroot -p111111 appshare_crawl"
# elif [ x${1} = x'video_dev_online' ];then 
#     PARAMS="-h192.168.1.21 -P3309 -uapsdev -papsdev602 video_dev_online"
elif [ x${1} = x'video_dev' ];then 
    PARAMS="-h192.168.1.21 -P3309 -uapsdev -papsdev602 video_dev"
elif [ x${1} = x'video' ];then 
    PARAMS="-h192.168.1.21 -P3309 -uapsdev -papsdev602 video"
else
    PARAMS=""
fi

/usr/bin/env `basename ${0}` ${PARAMS} ${2} ${3} ${4} ${5} ${6} ${7} ${8} ${9} ${10}
