#!/bin/bash

comm=`basename ${0}`
if [ x"${comm}" = x"smysql-passwd" ]
then

echo 'enter mysql passwd:'
read mysql_passwd
echo 'enter [your passwd]:'
echo ${mysql_passwd}|openssl enc -aes256 -e -a|xargs| tr -d ' '

else

config_file=~/.smysql/config
host_arg=${1}

source <(grep -m1 -iA20 "^ *host  *${host_arg} *$" ${config_file} |grep -m1 -B20 "^ *$"|sed 's/^ *\([^ ]\{1,\}\) *\([^ ]\{1,\}\) *$/\1=\2/')

if [ x"${host}" = x"" ]
then
    echo "invalid host: ${host_arg}"
    exit
fi

if [ x"${user}" = x"" ]
then
    echo 'user ???'
    exit
fi

if [ x"${hostname}" = x"" ]
then
    hostname=localhost
fi

if [ x"${port}" = x"" ]
then
    port=3306
fi

param_database=""
if [ ! x"${database}" = x"" ]
then
    param_database=-D${database}
fi

if [ x"${passwd}" = x"" ]
then
    echo "[ ${host} ] "${comm:1} -u${user} -P${port} -p -h${hostname} ${param_database} >&2
    echo "enter mysql passwd" >&2
else
    if [ x`echo ${passwd}|grep -o "^U2FsdGVkX1"` == x'U2FsdGVkX1' ]
    then
        echo "[ ${host} ] "${comm:1} -u${user} -P${port} -p AES256-decode\([your passwd]\) -h${hostname} ${param_database} >&2
        echo "enter [your passwd]:" >&2
        passwd=`echo ${passwd}|openssl enc -aes256 -d -a`
        if [ 0 != $? ]
        then
            echo "[your passwd] error" >&2
            exit
        fi
    else
        echo "[ ${host} ] "${comm:1} -u${user} -P${port} -p${passwd} -h${hostname} ${param_database} >&2
        passwd=$passwd
    fi
fi

case $# in
    1)
        ${comm:1} -u${user} -P${port} -p${passwd} -h${hostname} ${param_database}
        ;;
    2)
        ${comm:1} -u${user} -P${port} -p${passwd} -h${hostname} ${param_database} "${2}"
        ;;
    3)
        ${comm:1} -u${user} -P${port} -p${passwd} -h${hostname} ${param_database} "${2}" "${3}"
        ;;
    4)
        ${comm:1} -u${user} -P${port} -p${passwd} -h${hostname} ${param_database} "${2}" "${3}" "${4}"
        ;;
    5)
        ${comm:1} -u${user} -P${port} -p${passwd} -h${hostname} ${param_database} "${2}" "${3}" "${4}" "${5}"
        ;;
    6)
        ${comm:1} -u${user} -P${port} -p${passwd} -h${hostname} ${param_database} "${2}" "${3}" "${4}" "${5}" "${6}"
        ;;
    *)
        echo "bad num of args: ${#}"
        ;;
esac

fi
